title: AI Conference Deadlines (JUFO Levels)
description: Countdowns to top CV/ML/Robotics/AI conference deadlines
author: Bike

# domain: "aideadlin.es"
baseurl: "https://bisg-robotics.github.io/jufo_deadline"

# twitter_hashtag: machinelearning
# github_username: paperswithcode
# github_repo: ai-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
